[tool.poetry]
name = "spesh"
version = "0.1.0"
description = ""
authors = ["Magne F. Myhren <mfm@ssb.no>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
dapla-toolbelt = "^1.3.2"
ssb-klass-python = "^0.0.6"
cx-oracle = "^8.3.0"
dotenv = "^0.0.5"
openpyxl = "^3.1.2"
xlsxwriter = "^3.1.3"
python-dotenv = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
ipykernel = "^6.15.3"

[[tool.poetry.source]]
name = "nexus"
url = "http://pl-nexuspro-p.ssb.no:8081/repository/pypi-proxy/simple"
priority = "default"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
